# KPConv Parameter Analysis: S3DIS vs HQ vs ELECS

This notebook analyzes the KPConv parameter choices from the original S3DIS implementation and provides recommendations for your HQ and ELECS datasets based on the class distribution analysis.

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown

# Dataset characteristics analysis
datasets_info = {
    'S3DIS': {
        'domain': 'Indoor Scenes',
        'num_classes': 13,
        'point_density': 'High',
        'scene_scale': 'Room-level (5-15m)',
        'class_imbalance': 'Moderate',
        'dominant_classes': ['wall', 'ceiling', 'floor'],
        'object_sizes': 'Medium (furniture)',
        'spatial_structure': 'Structured (architectural)'
    },
    'ELECS': {
        'domain': 'Electrical Infrastructure',
        'num_classes': 10,
        'point_density': 'Medium',
        'scene_scale': 'Large outdoor (50-100m+)',
        'class_imbalance': 'High (ground 38%)',
        'dominant_classes': ['ground', 'media', 'tower'],
        'object_sizes': 'Large (towers, infrastructure)',
        'spatial_structure': 'Semi-structured'
    },
    'HQ': {
        'domain': 'Detailed Electrical/Power',
        'num_classes': 25,
        'point_density': 'Very High',
        'scene_scale': 'Equipment-level (detailed)',
        'class_imbalance': 'Extreme (ground 46%)',
        'dominant_classes': ['ground', 'metallic_support', 'media'],
        'object_sizes': 'Mixed (fine-grained equipment)',
        'spatial_structure': 'Highly detailed'
    }
}

# Display dataset comparison
df_comparison = pd.DataFrame(datasets_info).T
print("=== DATASET CHARACTERISTICS COMPARISON ===")
display(df_comparison)

=== DATASET CHARACTERISTICS COMPARISON ===

                          domain num_classes point_density                 scene_scale       class_imbalance                   dominant_classes                    object_sizes           spatial_structure
S3DIS              Indoor Scenes          13          High          Room-level (5-15m)              Moderate             [wall, ceiling, floor]              Medium (furniture)  Structured (architectural)
ELECS  Electrical Infrastructure          10        Medium    Large outdoor (50-100m+)     High (ground 38%)             [ground, media, tower]  Large (towers, infrastructure)             Semi-structured
HQ     Detailed Electrical/Power          25     Very High  Equipment-level (detailed)  Extreme (ground 46%)  [ground, metallic_support, media]  Mixed (fine-grained equipment)             Highly detailed

## KPConv S3DIS Parameter Analysis

The original KPConv paper chose specific parameters for S3DIS based on the dataset characteristics. Let's analyze why:

In [12]:
# Original S3DIS Parameters from KPConv
s3dis_params = {
    'in_radius': 1.2,           # Input sphere radius in meters
    'first_subsampling_dl': 0.03,  # First subsampling grid size in meters  
    'conv_radius': 2.5,         # Convolution radius in grid cells
    'KP_extent': 1.2,           # Kernel point influence radius
    'batch_num': 6,             # Number of point clouds per batch
    'num_kernel_points': 15,    # Number of kernel points
    'first_features_dim': 128,  # Initial feature dimension
    'in_features_dim': 5,       # Input features (XYZ + RGB + height)
    'learning_rate': 1e-2,      # Learning rate
    'max_epoch': 500,           # Maximum epochs
    'epoch_steps': 500,         # Steps per epoch
    'validation_size': 50       # Validation examples per epoch
}

print("=== S3DIS ORIGINAL PARAMETERS ===")
for param, value in s3dis_params.items():
    print(f"{param:25s}: {value}")

print("\n=== PARAMETER RATIONALE FOR S3DIS ===")
rationale = {
    'in_radius = 1.2m': 'Small radius for indoor furniture-scale objects. Captures local room context.',
    'first_subsampling_dl = 0.03m': 'Fine sampling (3cm) for detailed indoor geometry and small objects.',
    'conv_radius = 2.5': 'Standard value balancing receptive field vs computational cost.',
    'batch_num = 6': 'Moderate batch size balancing memory usage with gradient stability.',
    'num_kernel_points = 15': 'Good balance between expressiveness and computational cost.',
    'first_features_dim = 128': 'Rich feature representation for complex indoor scenes.',
    'in_features_dim = 5': 'XYZ + RGB + height above floor (important for indoor scenes).'
}

for param, reason in rationale.items():
    print(f"• {param:25s}: {reason}")

=== S3DIS ORIGINAL PARAMETERS ===
in_radius                : 1.2
first_subsampling_dl     : 0.03
conv_radius              : 2.5
KP_extent                : 1.2
batch_num                : 6
num_kernel_points        : 15
first_features_dim       : 128
in_features_dim          : 5
learning_rate            : 0.01
max_epoch                : 500
epoch_steps              : 500
validation_size          : 50

=== PARAMETER RATIONALE FOR S3DIS ===
• in_radius = 1.2m         : Small radius for indoor furniture-scale objects. Captures local room context.
• first_subsampling_dl = 0.03m: Fine sampling (3cm) for detailed indoor geometry and small objects.
• conv_radius = 2.5        : Standard value balancing receptive field vs computational cost.
• batch_num = 6            : Moderate batch size balancing memory usage with gradient stability.
• num_kernel_points = 15   : Good balance between expressiveness and computational cost.
• first_features_dim = 128 : Rich feature representation for complex indoor scenes.
• in_features_dim = 5      : XYZ + RGB + height above floor (important for indoor scenes).

## Parameter Recommendations for HQ and ELECS

Based on your bash history experiments and dataset characteristics, here are the recommended parameters:

In [13]:
# Recommended parameters based on dataset analysis and your experiments
recommended_params = {
    'ELECS': {
        'in_radius': 17.0,          # Large radius for outdoor infrastructure (from your experiments)
        'first_subsampling_dl': 0.3,  # Coarse sampling for large-scale outdoor scenes
        'conv_radius': 2.5,         # Keep standard
        'KP_extent': 1.2,           # Keep standard  
        'batch_num': 1,             # Small batch due to large scenes (memory constraint)
        'expected_N': 15000,        # Expected points per input sphere (from your tuning)
        'num_kernel_points': 15,    # Keep standard
        'first_features_dim': 64,   # Smaller than S3DIS (less complex than indoor)
        'in_features_dim': 4,       # XYZ + intensity (no RGB typically)
        'learning_rate': 1e-3,      # Lower LR for stability with large scenes
        'max_epochs': 100,          # From your experiments
        'class_weights': 'balanced' # Handle extreme class imbalance (ground 38%)
    },
    
    'HQ': {
        'in_radius': 6.0,           # Medium radius for detailed equipment-level analysis
        'first_subsampling_dl': 0.05, # Fine sampling for detailed equipment
        'conv_radius': 2.5,         # Keep standard
        'KP_extent': 1.2,           # Keep standard
        'batch_num': 1,             # Small batch due to high detail/memory usage
        'expected_N': 50000,        # High point density (from your experiments)
        'num_kernel_points': 15,    # Keep standard
        'first_features_dim': 128,  # High features for 25 fine-grained classes
        'in_features_dim': 6,       # XYZ + RGB + intensity + additional features
        'learning_rate': 1e-3,      # Conservative for complex multi-class problem
        'max_epochs': 100,          # From your experiments
        'class_weights': 'balanced', # Critical for extreme imbalance (ground 46%)
        'focal_loss_gamma': 2.0     # Help with extreme class imbalance
    }
}

# Display recommendations
for dataset, params in recommended_params.items():
    print(f"\n=== RECOMMENDED PARAMETERS FOR {dataset} ===")
    for param, value in params.items():
        print(f"{param:25s}: {value}")

print("\n=== KEY PARAMETER SCALING PRINCIPLES ===")
scaling_principles = {
    'in_radius': 'Scale with object/scene size: Indoor(1.2m) < Equipment(6m) < Infrastructure(17m)',
    'first_subsampling_dl': 'Scale with detail level: Fine detail(0.03-0.05m) < Outdoor(0.3m)',
    'batch_num': 'Inversely scale with scene size/memory: Large scenes = smaller batches',
    'expected_N': 'Scale with point density: Dense equipment(50k) > Outdoor infrastructure(15k)',
    'first_features_dim': 'Scale with task complexity: More classes = more features',
    'learning_rate': 'Lower for larger/more complex scenes for stability',
    'class_weights': 'CRITICAL for imbalanced datasets like yours (ground dominance)'
}

for principle, explanation in scaling_principles.items():
    print(f"• {principle:20s}: {explanation}")

=== RECOMMENDED PARAMETERS FOR ELECS ===
in_radius                : 17.0
first_subsampling_dl     : 0.3
conv_radius              : 2.5
KP_extent                : 1.2
batch_num                : 1
expected_N               : 15000
num_kernel_points        : 15
first_features_dim       : 64
in_features_dim          : 4
learning_rate            : 0.001
max_epochs               : 100
class_weights            : balanced

=== RECOMMENDED PARAMETERS FOR HQ ===
in_radius                : 6.0
first_subsampling_dl     : 0.05
conv_radius              : 2.5
KP_extent                : 1.2
batch_num                : 1
expected_N               : 50000
num_kernel_points        : 15
first_features_dim       : 128
in_features_dim          : 6
learning_rate            : 0.001
max_epochs               : 100
class_weights            : balanced
focal_loss_gamma         : 2.0

=== KEY PARAMETER SCALING PRINCIPLES ===
• in_radius           : Scale with object/scene size: Indoor(1.2m) < Equipment(6m) < Infrastructure(17m)
• first_subsampling_dl: Scale with detail level: Fine detail(0.03-0.05m) < Outdoor(0.3m)
• batch_num           : Inversely scale with scene size/memory: Large scenes = smaller batches
• expected_N          : Scale with point density: Dense equipment(50k) > Outdoor infrastructure(15k)
• first_features_dim  : Scale with task complexity: More classes = more features
• learning_rate       : Lower for larger/more complex scenes for stability
• class_weights       : CRITICAL for imbalanced datasets like yours (ground dominance)

## Class Imbalance Handling Strategies

Your datasets have significant class imbalance. Here are the strategies you should implement:

In [14]:
# Class imbalance analysis and solutions
class_imbalance_data = {
    'S3DIS': {
        'max_class_ratio': 25.9,  # wall
        'min_class_ratio': 2.1,   # column  
        'imbalance_ratio': 12.3,  # max/min
        'severity': 'Moderate'
    },
    'ELECS': {
        'max_class_ratio': 38.2,  # ground
        'min_class_ratio': 0.2,   # clutter
        'imbalance_ratio': 191.0, # max/min
        'severity': 'High'
    },
    'HQ': {
        'max_class_ratio': 46.1,  # ground
        'min_class_ratio': 0.1,   # multiple classes
        'imbalance_ratio': 461.0, # max/min
        'severity': 'Extreme'
    }
}

print("=== CLASS IMBALANCE ANALYSIS ===")
df_imbalance = pd.DataFrame(class_imbalance_data).T
display(df_imbalance)

print("\n=== RECOMMENDED SOLUTIONS BY DATASET ===")

solutions = {
    'ELECS (High Imbalance)': [
        "1. Weighted Cross-Entropy Loss: weight = 1 / class_frequency",
        "2. Focal Loss (γ=2): Focus on hard-to-classify examples",
        "3. Class-balanced sampling during training",
        "4. Data augmentation for minority classes",
        "5. Monitor per-class metrics (not just overall accuracy)"
    ],
    
    'HQ (Extreme Imbalance)': [
        "1. CRITICAL: Use Focal Loss (γ=2-5) + Class Weights",
        "2. Two-stage training: First balance, then fine-tune",
        "3. Oversample minority classes during batch creation",
        "4. Use F1-score and mIoU instead of accuracy",
        "5. Consider hierarchical classification (group similar classes)",
        "6. Potential class merging: Combine very rare classes (<1%)",
        "7. Use OHEM (Online Hard Example Mining)"
    ]
}

for dataset, solution_list in solutions.items():
    print(f"\n{dataset}:")
    for solution in solution_list:
        print(f"  {solution}")

# Calculate recommended class weights
print("\n=== SAMPLE CLASS WEIGHT CALCULATION ===")
print("For inverse frequency weighting:")
print("weight_i = total_samples / (num_classes × class_i_samples)")
print("\nExample for ELECS:")
print("- Ground (38.2%): weight = 1.0 / 0.382 = 2.62")
print("- Wall (6.6%): weight = 1.0 / 0.066 = 15.15") 
print("- Clutter (0.2%): weight = 1.0 / 0.002 = 500.0")
print("\n⚠️  Cap maximum weights to prevent gradient explosion (e.g., max_weight=100)")

=== CLASS IMBALANCE ANALYSIS ===

      max_class_ratio min_class_ratio imbalance_ratio  severity
S3DIS            25.9             2.1            12.3  Moderate
ELECS            38.2             0.2           191.0      High
HQ               46.1             0.1           461.0   Extreme

=== RECOMMENDED SOLUTIONS BY DATASET ===

ELECS (High Imbalance):
  1. Weighted Cross-Entropy Loss: weight = 1 / class_frequency
  2. Focal Loss (γ=2): Focus on hard-to-classify examples
  3. Class-balanced sampling during training
  4. Data augmentation for minority classes
  5. Monitor per-class metrics (not just overall accuracy)

HQ (Extreme Imbalance):
  1. CRITICAL: Use Focal Loss (γ=2-5) + Class Weights
  2. Two-stage training: First balance, then fine-tune
  3. Oversample minority classes during batch creation
  4. Use F1-score and mIoU instead of accuracy
  5. Consider hierarchical classification (group similar classes)
  6. Potential class merging: Combine very rare classes (<1%)
  7. Use OHEM (Online Hard Example Mining)

=== SAMPLE CLASS WEIGHT CALCULATION ===
For inverse frequency weighting:
weight_i = total_samples / (num_classes × class_i_samples)

Example for ELECS:
- Ground (38.2%): weight = 1.0 / 0.382 = 2.62
- Wall (6.6%): weight = 1.0 / 0.066 = 15.15
- Clutter (0.2%): weight = 1.0 / 0.002 = 500.0

⚠️  Cap maximum weights to prevent gradient explosion (e.g., max_weight=100)

## Training Configuration Recommendations

Based on your experiments and dataset analysis, here are complete training configurations:

In [15]:
print("=== COMPLETE TRAINING CONFIGURATIONS ===")

elecs_config = """
# ELECS Dataset Configuration
python src/train_elecs.py \\
    common.in_radius=17.0 \\
    common.first_subsampling_dl=0.3 \\
    common.expected_N=15000 \\
    common.batch_num=1 \\
    model.first_features_dim=64 \\
    model.in_features_dim=4 \\
    optimizer.learning_rate=1e-3 \\
    trainer.max_epochs=100 \\
    loss.use_focal_loss=true \\
    loss.focal_gamma=2.0 \\
    loss.class_weights=balanced \\
    loss.weight_cap=100.0 \\
    data.use_potentials=true \\
    trainer.val_check_interval=0.25
"""

hq_config = """
# HQ Dataset Configuration  
python src/train_hq.py \\
    common.in_radius=6.0 \\
    common.first_subsampling_dl=0.05 \\
    common.expected_N=50000 \\
    common.batch_num=1 \\
    model.first_features_dim=128 \\
    model.in_features_dim=6 \\
    optimizer.learning_rate=1e-3 \\
    trainer.max_epochs=100 \\
    loss.use_focal_loss=true \\
    loss.focal_gamma=3.0 \\
    loss.class_weights=balanced \\
    loss.weight_cap=50.0 \\
    data.use_potentials=true \\
    trainer.val_check_interval=0.1 \\
    trainer.gradient_clip_val=1.0
"""

print("ELECS Configuration:")
print(elecs_config)
print("\nHQ Configuration:")
print(hq_config)

print("\n=== KEY DIFFERENCES FROM S3DIS ===")
differences = [
    "🔍 SPATIAL SCALE: Much larger in_radius for outdoor scenes (17m vs 1.2m)",
    "📏 SUBSAMPLING: Coarser for ELECS (0.3m), finer for HQ details (0.05m)", 
    "🎯 BATCH SIZE: Reduced to 1 due to memory constraints with large scenes",
    "🧠 FEATURES: Adapted input features (no RGB for ELECS, rich features for HQ)",
    "⚖️  LOSS FUNCTION: Focal loss + class weights for extreme imbalance",
    "📊 MONITORING: More frequent validation due to imbalanced metrics",
    "🎓 LEARNING RATE: Conservative (1e-3) for stability with complex scenes"
]

for diff in differences:
    print(f"  {diff}")

print("\n=== CRITICAL SUCCESS FACTORS ===")
success_factors = [
    "✅ Class imbalance handling is CRITICAL (focal loss + weights)",
    "✅ Monitor per-class IoU, not just overall accuracy", 
    "✅ Use early stopping based on mean IoU",
    "✅ Regular validation to catch overfitting on dominant classes",
    "✅ Gradient clipping for training stability",
    "✅ Consider curriculum learning: easy → hard examples"
]

for factor in success_factors:
    print(f"  {factor}")

=== COMPLETE TRAINING CONFIGURATIONS ===
ELECS Configuration:

# ELECS Dataset Configuration
python src/train_elecs.py \
    common.in_radius=17.0 \
    common.first_subsampling_dl=0.3 \
    common.expected_N=15000 \
    common.batch_num=1 \
    model.first_features_dim=64 \
    model.in_features_dim=4 \
    optimizer.learning_rate=1e-3 \
    trainer.max_epochs=100 \
    loss.use_focal_loss=true \
    loss.focal_gamma=2.0 \
    loss.class_weights=balanced \
    loss.weight_cap=100.0 \
    data.use_potentials=true \
    trainer.val_check_interval=0.25


HQ Configuration:

# HQ Dataset Configuration
python src/train_hq.py \
    common.in_radius=6.0 \
    common.first_subsampling_dl=0.05 \
    common.expected_N=50000 \
    common.batch_num=1 \
    model.first_features_dim=128 \
    model.in_features_dim=6 \
    optimizer.learning_rate=1e-3 \
    trainer.max_epochs=100 \
    loss.use_focal_loss=true \
    loss.focal_gamma=3.0 \
    loss.class_weights=balanced \
    loss.weight_cap=50.0 \
    data.use_potentials=true \
    trainer.val_check_interval=0.1 \
    trainer.gradient_clip_val=1.0


=== KEY DIFFERENCES FROM S3DIS ===
  🔍 SPATIAL SCALE: Much larger in_radius for outdoor scenes (17m vs 1.2m)
  📏 SUBSAMPLING: Coarser for ELECS (0.3m), finer for HQ details (0.05m)
  🎯 BATCH SIZE: Reduced to 1 due to memory constraints with large scenes
  🧠 FEATURES: Adapted input features (no RGB for ELECS, rich features for HQ)
  ⚖️  LOSS FUNCTION: Focal loss + class weights for extreme imbalance
  📊 MONITORING: More frequent validation due to imbalanced metrics
  🎓 LEARNING RATE: Conservative (1e-3) for stability with complex scenes

=== CRITICAL SUCCESS FACTORS ===
  ✅ Class imbalance handling is CRITICAL (focal loss + weights)
  ✅ Monitor per-class IoU, not just overall accuracy
  ✅ Use early stopping based on mean IoU
  ✅ Regular validation to catch overfitting on dominant classes
  ✅ Gradient clipping for training stability
  ✅ Consider curriculum learning: easy → hard examples

In [16]:
import pandas as pd
import os
from IPython.display import display

# Folder where CSVs are saved
output_folder = "/home/nikhita_rayanki/projects/datasets/outputs_pie_HQ_v2_Electrical_new"

# File paths
filewise_csv = os.path.join(output_folder, "filewise_class_counts_and_densities.csv")
overall_csv = os.path.join(output_folder, "overall_class_counts_and_densities.csv")

# Read CSVs
filewise_df = pd.read_csv(filewise_csv)
overall_df = pd.read_csv(overall_csv)

# Reorder filewise_df to match numerical order (3_1, 3_2, 3_3, 3_4, 4_1, 4_2, 4_3, 4_4, etc.)
desired_order = [
    "03_1_v2_filtered.ply",
    "03_2_v2_filtered.ply", 
    "03_3_v2_filtered.ply",
    "03_4_v2_filtered.ply",
    "04_1_v2_filtered.ply",
    "04_2_v2_filtered.ply",
    "04_3_v2_filtered.ply",
    "04_4_v2_filtered.ply",
    "05_v2_filtered.ply",
    "06_v2_filtered.ply"
]

# Create a mapping for sorting
if 'file_path' in filewise_df.columns:
    # Extract just the filename from the path
    filewise_df['filename'] = filewise_df['file_path'].apply(lambda x: os.path.basename(x))
    
    # Create a custom sort order
    order_dict = {filename: idx for idx, filename in enumerate(desired_order)}
    filewise_df['sort_order'] = filewise_df['filename'].map(order_dict)
    
    # Sort by the custom order, putting unmapped files at the end
    filewise_df = filewise_df.sort_values('sort_order', na_last=True)
    
    # Drop the helper columns
    filewise_df = filewise_df.drop(['filename', 'sort_order'], axis=1)
    
    # Reset index to get clean row numbers 0, 1, 2, etc.
    filewise_df = filewise_df.reset_index(drop=True)

# Optional: set Pandas display options for full width and scrollable view
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.width', 2000)        # wide display

# Display first 10 rows of filewise stats nicely
print("===== Filewise Class Counts & Densities =====")
display(filewise_df.head(10))

# Display overall stats nicely
print("\n===== Overall Class Counts & Densities =====")
display(overall_df)

===== Filewise Class Counts & Densities =====

                   file  High Voltage Power Transformer  Grounding Transformer  Medium Voltage Power Transformer  Voltage Transformer  Current Transformer  Capacitor Bank  Circuit Breaker  Recloser  Surge Arrester  Disconnect Switch  Actuator  Junction Box   Busbar    Wire  Insulator  High Voltage Power Transformer (%)  Grounding Transformer (%)  Medium Voltage Power Transformer (%)  Voltage Transformer (%)  Current Transformer (%)  Capacitor Bank (%)  Circuit Breaker (%)  Recloser (%)  Surge Arrester (%)  Disconnect Switch (%)  Actuator (%)  Junction Box (%)  Busbar (%)   Wire (%)  Insulator (%)  total_points
0  04_2_v2_filtered.ply                         3648376                 631954                            281144                41437                    0               0                0   1714587           93716             204088    279061       1305335   642479  819405     295154                           36.642289                   6.347000                              2.823656                 0.416171                 0.000000            0.000000             0.000000     17.220372            0.941232               2.049748      2.802736         13.110069    6.452707   8.229655       2.964365       9956736
1  03_2_v2_filtered.ply                               0                      0                                 0               172230               636580               0           446749         0               0             283311    595526       1074098        0  900603    1163435                            0.000000                   0.000000                              0.000000                 3.266552                12.073516            0.000000             8.473140      0.000000            0.000000               5.373339     11.294877         20.371579    0.000000  17.081034      22.065964       5272532
2  04_3_v2_filtered.ply                               0                      0                             58167                    0                37352         1138966                0    408945               0              27900    138061         75169   196225   65615     109253                            0.000000                   0.000000                              2.578721                 0.000000                 1.655928           50.493848             0.000000     18.129783            0.000000               1.236892      6.120667          3.332472    8.699255   2.908914       4.843520       2255653
3  03_3_v2_filtered.ply                               0                      0                                 0               164387               672161               0          1091988         0               0             208312    460109       1633084        0  658841     959657                            0.000000                   0.000000                              0.000000                 2.810736                11.492802            0.000000            18.671125      0.000000            0.000000               3.561778      7.867076         27.922939    0.000000  11.265053      16.408491       5848539
4  03_1_v2_filtered.ply                               0                      0                                 0                    0                    0               0           492400         0               0              67589     73729        542907        0  456211     494276                            0.000000                   0.000000                              0.000000                 0.000000                 0.000000            0.000000            23.148758      0.000000            0.000000               3.177501      3.466155         25.523198    0.000000  21.447437      23.236952       2127112
5  04_4_v2_filtered.ply                               0                      0                             61875                    0                49388          967987                0    404434               0              33908    124069         69441   174659   82585      84237                            0.000000                   0.000000                              3.014494                 0.000000                 2.406139           47.159457             0.000000     19.703661            0.000000               1.651967      6.044530          3.383103    8.509230   4.023467       4.103951       2052583
6    06_v2_filtered.ply                               0                      0                                 0                    0                    0               0                0         0               0                  0         0             0        0       0          0                            0.000000                   0.000000                              0.000000                 0.000000                 0.000000            0.000000             0.000000      0.000000            0.000000               0.000000      0.000000          0.000000    0.000000   0.000000       0.000000             0
7  03_4_v2_filtered.ply                               0                      0                                 0               150158               292832               0                0         0               0              61121     74741        278677        0  445488     323625                            0.000000                   0.000000                              0.000000                 9.231165                18.002240            0.000000             0.000000      0.000000            0.000000               3.757496      4.594803         17.132043    0.000000  27.386973      19.895281       1626642
8  04_1_v2_filtered.ply                         3857421                 731117                                 0                40827                    0               0                0   2763979           96130             259436    827334       1031803  1006015  905619     511958                           32.060644                   6.076620                              0.000000                 0.339330                 0.000000            0.000000             0.000000     22.972589            0.798977               2.156281      6.876320          8.575748    8.361413   7.526979       4.255098      12031639
9    05_v2_filtered.ply                         3221363                 938767                            186408                10971                    0               0                0   1489656           75069             194069         0        324595   564601  669262     195762                           40.929466                  11.927632                              2.368432                 0.139394                 0.000000            0.000000             0.000000     18.927027            0.953799               2.465770      0.000000          4.124186    7.173615   8.503399       2.487281       7870523

===== Overall Class Counts & Densities =====

  Unnamed: 0  High Voltage Power Transformer  Grounding Transformer  Medium Voltage Power Transformer  Voltage Transformer  Current Transformer  Capacitor Bank  Circuit Breaker  Recloser  Surge Arrester  Disconnect Switch  Actuator  Junction Box   Busbar     Wire  Insulator  High Voltage Power Transformer (%)  Grounding Transformer (%)  Medium Voltage Power Transformer (%)  Voltage Transformer (%)  Current Transformer (%)  Capacitor Bank (%)  Circuit Breaker (%)  Recloser (%)  Surge Arrester (%)  Disconnect Switch (%)  Actuator (%)  Junction Box (%)  Busbar (%)   Wire (%)  Insulator (%)  total_points
0    overall                        10727160                2301838                            587594               580010              1688313         2106953          2031137   6781601          264915            1339734   2572630       6335109  2583979  5003629    4137357                           21.873433                   4.693609                              1.198145                 1.182681                 3.442589            4.296225             4.141631     13.828161             0.54018               2.731812      5.245773         12.917732    5.268915  10.202751       8.436362      49041959

In [17]:
import pandas as pd
import os
from IPython.display import display

# Folder where CSVs are saved
output_folder = "/home/nikhita_rayanki/projects/datasets/outputs_pie_HQ_v2_new"

# File paths
filewise_csv = os.path.join(output_folder, "filewise_class_counts_and_densities.csv")
overall_csv = os.path.join(output_folder, "overall_class_counts_and_densities.csv")

# Read CSVs
filewise_df = pd.read_csv(filewise_csv)
overall_df = pd.read_csv(overall_csv)

# Reorder filewise_df to match numerical order (3_1, 3_2, 3_3, 3_4, 4_1, 4_2, 4_3, 4_4, etc.)
desired_order = [
    "03_1_v2_filtered.ply",
    "03_2_v2_filtered.ply", 
    "03_3_v2_filtered.ply",
    "03_4_v2_filtered.ply",
    "04_1_v2_filtered.ply",
    "04_2_v2_filtered.ply",
    "04_3_v2_filtered.ply",
    "04_4_v2_filtered.ply",
    "05_v2_filtered.ply",
    "06_v2_filtered.ply"
]

# Create a mapping for sorting
if 'file_path' in filewise_df.columns:
    # Extract just the filename from the path
    filewise_df['filename'] = filewise_df['file_path'].apply(lambda x: os.path.basename(x))
    
    # Create a custom sort order
    order_dict = {filename: idx for idx, filename in enumerate(desired_order)}
    filewise_df['sort_order'] = filewise_df['filename'].map(order_dict)
    
    # Sort by the custom order, putting unmapped files at the end
    filewise_df = filewise_df.sort_values('sort_order', na_last=True)
    
    # Drop the helper columns
    filewise_df = filewise_df.drop(['filename', 'sort_order'], axis=1)
    
    # Reset index to get clean row numbers 0, 1, 2, etc.
    filewise_df = filewise_df.reset_index(drop=True)

# Optional: set Pandas display options for full width and scrollable view
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.width', 2000)        # wide display

# Display first 10 rows of filewise stats nicely
print("===== Filewise Class Counts & Densities =====")
display(filewise_df.head(10))

# Display overall stats nicely
print("\n===== Overall Class Counts & Densities =====")
display(overall_df)

===== Filewise Class Counts & Densities =====

          file  No Classification  High Voltage Power Transformer  Grounding Transformer  Medium Voltage Power Transformer  Voltage Transformer  Current Transformer  Capacitor Bank  Circuit Breaker  Recloser  Surge Arrester  Disconnect Switch  Actuator  Junction Box   Busbar    Wire  Insulator  Metallic Support Structure  Concrete Base  Building   Lamp    Pipe  Nameplate  Artifact  Vegetation    Ground    Fence  No Classification (%)  High Voltage Power Transformer (%)  Grounding Transformer (%)  Medium Voltage Power Transformer (%)  Voltage Transformer (%)  Current Transformer (%)  Capacitor Bank (%)  Circuit Breaker (%)  Recloser (%)  Surge Arrester (%)  Disconnect Switch (%)  Actuator (%)  Junction Box (%)  Busbar (%)  Wire (%)  Insulator (%)  Metallic Support Structure (%)  Concrete Base (%)  Building (%)  Lamp (%)  Pipe (%)  Nameplate (%)  Artifact (%)  Vegetation (%)  Ground (%)  Fence (%)  total_points
0  03_4_v2.ply              25324                               0                      0                                 0               150158               292832               0                0         0               0              61121     74741        278677        0  445488     323625                     6339213         195869         0      0       0      17897     67089      205511   5786634   977623               0.166148                            0.000000                   0.000000                              0.000000                 0.985172                 1.921243            0.000000             0.000000      0.000000            0.000000               0.401009      0.490369          1.828373    0.000000  2.922804       2.123273                       41.590968           1.285078      0.000000  0.000000  0.000000       0.117420      0.440164        1.348338   37.965550   6.414091      15241802
1  04_1_v2.ply              60002                         3857421                 731117                                 0                40827                    0               0                0   2763979           96130             259436    827334       1031803  1006015  905619     511958                     8287650        1664158         0  87776       0      17207         0           0   5692341        0               0.215385                           13.846721                   2.624441                              0.000000                 0.146554                 0.000000            0.000000             0.000000      9.921667            0.345071               0.931280      2.969824          3.703793    3.611223  3.250839       1.837741                       29.749611           5.973714      0.000000  0.315084  0.000000       0.061767      0.000000        0.000000   20.433408   0.000000      27858011
2  03_2_v2.ply              26479                               0                      0                                 0               172230               636580               0           446749         0               0             283311    595526       1074098        0  900603    1163435                    13537166         307392         0  93057       0          0         0           0  35501281   400160               0.048023                            0.000000                   0.000000                              0.000000                 0.312361                 1.154520            0.000000             0.810237      0.000000            0.000000               0.513821      1.080063          1.948015    0.000000  1.633360       2.110039                       24.551396           0.557495      0.000000  0.168771  0.000000       0.000000      0.000000        0.000000   64.386150   0.725742      55138071
3  04_4_v2.ply              34672                               0                      0                             61875                    0                49388          967987                0    404434               0              33908    124069         69441   174659   82585      84237                     2579793         388344         0  14692       0      66682         0      579915   2453674  1066810               0.374546                            0.000000                   0.000000                              0.668407                 0.000000                 0.533516           10.456717             0.000000      4.368914            0.000000               0.366292      1.340260          0.750139    1.886761  0.892128       0.909973                       27.868314           4.195101      0.000000  0.158711  0.000000       0.720335      0.000000        6.264554   26.505909  11.524257       9257083
4  04_3_v2.ply              24784                               0                      0                             58167                    0                37352         1138966                0    408945               0              27900    138061         75169   196225   65615     109253                     2716670         447082         0  19878       0      50147         0       71934   1541879   825280               0.310660                            0.000000                   0.000000                              0.729105                 0.000000                 0.468196           14.276587             0.000000      5.125999            0.000000               0.349718      1.730552          0.942220    2.459620  0.822464       1.369453                       34.052620           5.604035      0.000000  0.249165  0.000000       0.628577      0.000000        0.901670   19.326977  10.344630       7977859
5  03_1_v2.ply               8019                               0                      0                                 0                    0                    0               0           492400         0               0              67589     73729        542907        0  456211     494276                     4927756         338247         0      0       0          0     79880      533095  25027366   590414               0.023843                            0.000000                   0.000000                              0.000000                 0.000000                 0.000000            0.000000             1.464087      0.000000            0.000000               0.200967      0.219223          1.614263    0.000000  1.356483       1.469665                       14.652035           1.005733      0.000000  0.000000  0.000000       0.000000      0.237513        1.585088   74.415582   1.755518      33631889
6  04_2_v2.ply              37271                         3648376                 631954                            281144                41437                    0               0                0   1714587           93716             204088    279061       1305335   642479  819405     295154                     6625317        1252903         0  53311  151094      38936     47846           0  10644915        0               0.129312                           12.658092                   2.192573                              0.975433                 0.143766                 0.000000            0.000000             0.000000      5.948784            0.325149               0.708086      0.968206          4.528878    2.229090  2.842937       1.024041                       22.986631           4.346965      0.000000  0.184963  0.524223       0.135089      0.166002        0.000000   36.932682   0.000000      28822480
7    06_v2.ply                  0                               0                      0                                 0                    0                    0               0                0         0               0                  0         0             0        0       0          0                           0              0  13180691  24127       0          0   3380152      545518   7538418  1467039               0.000000                            0.000000                   0.000000                              0.000000                 0.000000                 0.000000            0.000000             0.000000      0.000000            0.000000               0.000000      0.000000          0.000000    0.000000  0.000000       0.000000                        0.000000           0.000000     50.431278  0.092313  0.000000       0.000000     12.932963        2.087233   28.843105   5.613109      26135945
8    05_v2.ply              86812                         3221363                 938767                            186408                10971                    0               0                0   1489656           75069             194069         0        324595   564601  669262     195762                     5084730         713089    341819  45582       0      58836         8           0   5544992   542300               0.427643                           15.868690                   4.624441                              0.918261                 0.054044                 0.000000            0.000000             0.000000      7.338164            0.369796               0.955999      0.000000          1.598981    2.781269  3.296838       0.964339                       25.047784           3.512733      1.683828  0.224541  0.000000       0.289831      0.000039        0.000000   27.315071   2.671413      20300119
9  03_3_v2.ply              28769                               0                      0                                 0               164387               672161               0          1091988         0               0             208312    460109       1633084        0  658841     959657                     8778898        1110053     31870      0       0       5641     25874           0  20562095   423070               0.078145                            0.000000                   0.000000                              0.000000                 0.446524                 1.825790            0.000000             2.966165      0.000000            0.000000               0.565838      1.249793          4.435943    0.000000  1.789609       2.606715                       23.846105           3.015235      0.086568  0.000000  0.000000       0.015323      0.070282        0.000000   55.852782   1.149184      36814809

===== Overall Class Counts & Densities =====

  Unnamed: 0  No Classification  High Voltage Power Transformer  Grounding Transformer  Medium Voltage Power Transformer  Voltage Transformer  Current Transformer  Capacitor Bank  Circuit Breaker  Recloser  Surge Arrester  Disconnect Switch  Actuator  Junction Box   Busbar     Wire  Insulator  Metallic Support Structure  Concrete Base  Building    Lamp    Pipe  Nameplate  Artifact  Vegetation     Ground    Fence  No Classification (%)  High Voltage Power Transformer (%)  Grounding Transformer (%)  Medium Voltage Power Transformer (%)  Voltage Transformer (%)  Current Transformer (%)  Capacitor Bank (%)  Circuit Breaker (%)  Recloser (%)  Surge Arrester (%)  Disconnect Switch (%)  Actuator (%)  Junction Box (%)  Busbar (%)  Wire (%)  Insulator (%)  Metallic Support Structure (%)  Concrete Base (%)  Building (%)  Lamp (%)  Pipe (%)  Nameplate (%)  Artifact (%)  Vegetation (%)  Ground (%)  Fence (%)  total_points
0    overall             332132                        10727160                2301838                            587594               580010              1688313         2106953          2031137   6781601          264915            1339734   2572630       6335109  2583979  5003629    4137357                    58877193        6417137  13554380  338423  151094     255346   3600849     1935973  120293595  6292696               0.127167                            4.107221                   0.881329                              0.224978                 0.222075                 0.646422            0.806711             0.777683      2.596543            0.101431               0.512958       0.98501           2.42559    0.989355  1.915792       1.584113                       22.542932           2.456997      5.189708  0.129576  0.057851       0.097767      1.378695        0.741246   46.058077   2.409351     261178068

## HQ Dataset Analysis: Electrical Components vs Complete Substation

Comparative analysis of:
- **HQ_Electrical**: Only electrical components/equipment from the substation
- **HQ_Complete**: Entire substation including electrical + structural + support infrastructure

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown

# Load both datasets for comparison
electrical_only_folder = "/home/nikhita_rayanki/projects/datasets/outputs_pie_HQ_v2_Electrical_new"
complete_substation_folder = "/home/nikhita_rayanki/projects/datasets/outputs_pie_HQ_v2_new"

# Read electrical components only dataset
elec_overall = pd.read_csv(os.path.join(electrical_only_folder, "overall_class_counts_and_densities.csv"))
elec_filewise = pd.read_csv(os.path.join(electrical_only_folder, "filewise_class_counts_and_densities.csv"))

# Read complete substation dataset (electrical + structural)
complete_overall = pd.read_csv(os.path.join(complete_substation_folder, "overall_class_counts_and_densities.csv"))
complete_filewise = pd.read_csv(os.path.join(complete_substation_folder, "filewise_class_counts_and_densities.csv"))

print("=== DATASET OVERVIEW ===")
print(f"HQ Electrical Components Only:")
print(f"  - Total files: {len(elec_filewise)}")
print(f"  - Total points: {elec_overall.iloc[0]['total_points']:,}")

print(f"\nHQ Complete Substation (All Infrastructure):")
print(f"  - Total files: {len(complete_filewise)}")
print(f"  - Total points: {complete_overall.iloc[0]['total_points']:,}")

# Extract class density columns (those ending with %)
elec_classes = [col for col in elec_overall.columns if col.endswith('(%)') and not col.startswith('Unnamed')]
complete_classes = [col for col in complete_overall.columns if col.endswith('(%)') and not col.startswith('Unnamed')]

print(f"\nElectrical-only dataset classes: {len(elec_classes)}")
print(f"Complete substation dataset classes: {len(complete_classes)}")

# Get class percentages
elec_percentages = {}
for col in elec_classes:
    class_name = col.replace(' (%)', '')
    elec_percentages[class_name] = elec_overall.iloc[0][col]

complete_percentages = {}
for col in complete_classes:
    class_name = col.replace(' (%)', '')
    complete_percentages[class_name] = complete_overall.iloc[0][col]

print(f"\nElectrical-only classes: {list(elec_percentages.keys())}")
print(f"Complete substation classes: {list(complete_percentages.keys())}")

# Create comparison dataframe
all_classes = set(elec_percentages.keys()) | set(complete_percentages.keys())
comparison_data = []

for class_name in all_classes:
    elec_pct = elec_percentages.get(class_name, 0.0)
    complete_pct = complete_percentages.get(class_name, 0.0)
    difference = elec_pct - complete_pct
    
    comparison_data.append({
        'Class': class_name,
        'Electrical_Only_%': elec_pct,
        'Complete_Substation_%': complete_pct,
        'Difference_%': difference,
        'Present_in_Electrical': class_name in elec_percentages,
        'Present_in_Complete': class_name in complete_percentages
    })

comparison_df = pd.DataFrame(comparison_data)
comparison_df = comparison_df.sort_values('Electrical_Only_%', ascending=False)

print("\n=== CLASS DISTRIBUTION COMPARISON ===")
display(comparison_df)

=== DATASET OVERVIEW ===
HQ Electrical Components Only:
  - Total files: 10
  - Total points: 49,041,959

HQ Complete Substation (All Infrastructure):
  - Total files: 10
  - Total points: 261,178,068

Electrical-only dataset classes: 15
Complete substation dataset classes: 26

Electrical-only classes: ['High Voltage Power Transformer', 'Grounding Transformer', 'Medium Voltage Power Transformer', 'Voltage Transformer', 'Current Transformer', 'Capacitor Bank', 'Circuit Breaker', 'Recloser', 'Surge Arrester', 'Disconnect Switch', 'Actuator', 'Junction Box', 'Busbar', 'Wire', 'Insulator']
Complete substation classes: ['No Classification', 'High Voltage Power Transformer', 'Grounding Transformer', 'Medium Voltage Power Transformer', 'Voltage Transformer', 'Current Transformer', 'Capacitor Bank', 'Circuit Breaker', 'Recloser', 'Surge Arrester', 'Disconnect Switch', 'Actuator', 'Junction Box', 'Busbar', 'Wire', 'Insulator', 'Metallic Support Structure', 'Concrete Base', 'Building', 'Lamp', 'Pipe', 'Nameplate', 'Artifact', 'Vegetation', 'Ground', 'Fence']

=== CLASS DISTRIBUTION COMPARISON ===

                               Class  Electrical_Only_%  Complete_Substation_%  Difference_%  Present_in_Electrical  Present_in_Complete
22    High Voltage Power Transformer          21.873433               4.107221     17.766212                   True                 True
0                           Recloser          13.828161               2.596543     11.231618                   True                 True
16                      Junction Box          12.917732               2.425590     10.492142                   True                 True
3                               Wire          10.202751               1.915792      8.286959                   True                 True
5                          Insulator           8.436362               1.584113      6.852248                   True                 True
24                            Busbar           5.268915               0.989355      4.279559                   True                 True
9                           Actuator           5.245773               0.985010      4.260763                   True                 True
20             Grounding Transformer           4.693609               0.881329      3.812280                   True                 True
7                     Capacitor Bank           4.296225               0.806711      3.489514                   True                 True
12                   Circuit Breaker           4.141631               0.777683      3.363948                   True                 True
17               Current Transformer           3.442589               0.646422      2.796167                   True                 True
10                 Disconnect Switch           2.731812               0.512958      2.218854                   True                 True
11  Medium Voltage Power Transformer           1.198145               0.224978      0.973167                   True                 True
18               Voltage Transformer           1.182681               0.222075      0.960607                   True                 True
1                     Surge Arrester           0.540180               0.101431      0.438749                   True                 True
6                  No Classification           0.000000               0.127167     -0.127167                  False                 True
2                             Ground           0.000000              46.058077    -46.058077                  False                 True
4         Metallic Support Structure           0.000000              22.542932    -22.542932                  False                 True
8                           Artifact           0.000000               1.378695     -1.378695                  False                 True
14                             Fence           0.000000               2.409351     -2.409351                  False                 True
13                     Concrete Base           0.000000               2.456997     -2.456997                  False                 True
15                         Nameplate           0.000000               0.097767     -0.097767                  False                 True
21                          Building           0.000000               5.189708     -5.189708                  False                 True
19                        Vegetation           0.000000               0.741246     -0.741246                  False                 True
23                              Pipe           0.000000               0.057851     -0.057851                  False                 True
25                              Lamp           0.000000               0.129576     -0.129576                  False                 True

In [19]:
import os

# Check the output directory
output_tables_dir = "/home/nikhita_rayanki/projects/datasets/output_tables"

# Summary of all saved table images
print("=== SAVED TABLE IMAGES SUMMARY ===")
saved_images = [
    'dataset_characteristics_comparison.png',
    'class_imbalance_analysis.png', 
    'HQ_electrical_vs_complete_comparison.png',
    'HQ_electrical_vs_complete_significant_classes.png'
]

print("The following tables have been saved as PNG images:")
for i, image in enumerate(saved_images, 1):
    full_path = os.path.join(output_tables_dir, image)
    if os.path.exists(full_path):
        size_kb = os.path.getsize(full_path) // 1024
        print(f"  {i}. ✅ {image} ({size_kb} KB)")
    else:
        print(f"  {i}. ❌ {image} (not found)")

print(f"\n📁 Images saved in directory: {output_tables_dir}")
print("🎨 All images are saved with 300 DPI for high quality")
print("📊 Tables are professionally formatted with alternating row colors")
print("💾 Files are ready for presentations or reports!")

# Show full paths for easy access
print(f"\n📂 Full file paths:")
for image in saved_images:
    full_path = os.path.join(output_tables_dir, image)
    print(f"  {full_path}")

=== SAVED TABLE IMAGES SUMMARY ===
The following tables have been saved as PNG images:
  1. ✅ dataset_characteristics_comparison.png (210 KB)
  2. ❌ class_imbalance_analysis.png (not found)
  3. ❌ HQ_electrical_vs_complete_comparison.png (not found)
  4. ❌ HQ_electrical_vs_complete_significant_classes.png (not found)

📁 Images saved in directory: /home/nikhita_rayanki/projects/datasets/output_tables
🎨 All images are saved with 300 DPI for high quality
📊 Tables are professionally formatted with alternating row colors
💾 Files are ready for presentations or reports!

📂 Full file paths:
  /home/nikhita_rayanki/projects/datasets/output_tables/dataset_characteristics_comparison.png
  /home/nikhita_rayanki/projects/datasets/output_tables/class_imbalance_analysis.png
  /home/nikhita_rayanki/projects/datasets/output_tables/HQ_electrical_vs_complete_comparison.png
  /home/nikhita_rayanki/projects/datasets/output_tables/HQ_electrical_vs_complete_significant_classes.png